apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: faceit-technical-test
build:
  artifacts:
  - image: build-grpc_event_server
    context: build/grpcsrvr
    docker:
      dockerfile: Dockerfile
  - image: build-user
    context: build/user
    docker:
      dockerfile: Dockerfile
  - image: build-usrgrpc
    context: build/usrgrpc
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - build/usrgrpc/deployment.yaml
    - build/grpcsrvr/deployment.yaml
    - build/user/deployment.yaml
portForward:
- resourceType: service
  resourceName: build-user
  port: 8089
- resourceType: service
  resourceName: build-user_grpc
  port: 8092
