apiVersion: v1
kind: Service
metadata:
  name: build-user
  labels:
    app: build-user
spec:
  ports:
  - port: 8089
    protocol: TCP
  clusterIP: None
  selector:
    app: build-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-user
  labels:
    app: build-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-user
  template:
    metadata:
      labels:
        app: build-user
    spec:
      containers:
      - name: build-user
        image: build-user
