version: '3.8'
services:
  postgresql:
    image: postgres:14.3-alpine
    hostname: postgresql
    container_name: postgresql
    restart: always
    command: -p 5438
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=faceit
    ports:
      - "5438:5438"
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ../../init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - faceit
  grpcsrvr:
    build:
      context: ../
      dockerfile: build/grpcsrv/Dockerfile
    container_name: grpcsrv
    pull_policy: build
    restart: always
    environment:
      - ENV=docker
    depends_on:
      - postgresql
    networks:
      - faceit
  grpc_server_test:
    build:
      context: ../
      dockerfile: build/grpcsrv/Dockerfile
    container_name: grpc_server_test
    pull_policy: build
    restart: always
    ports:
      - "50052:50052"
    environment:
      - ENV=grpc_test_docker
    depends_on:
      - postgresql
    networks:
      - faceit
  user:
    build:
      context: ../
      dockerfile:  build/user/Dockerfile
    container_name: user_service
    pull_policy: build
    ports:
      - "8089:8089"
    restart: always
    environment:
      - ENV=docker
    depends_on:
      - postgresql
    networks:
      - faceit
  usrgrpc:
    build:
      context: ../
      dockerfile: build/usrgrpc/Dockerfile
    container_name: usrgrpc
    hostname: usrgrpc
    pull_policy: build
    ports:
      - "8092:8092"
    restart: always
    environment:
      - ENV=docker
    depends_on:
      - postgresql
    networks:
      - faceit
volumes:
  postgresql:
    driver: local
networks:
  faceit:
    name: faceit