name: Faceit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build the stack
        run: docker-compose -f  deployment/ci/docker-compose.yml up -d
      - name: Test
        run:  ENV="test" go test -v test/user_service_test.go  -coverpkg=./internal/user/... -coverprofile=coverage.out
      - run:  go vet ./...